title: libewa.xyz
author:
  name: libewa
  email: linus@libewa.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Mediocre Swift and TypeScript code,
  with a bit of Python and C++.
baseurl: "" # the subpath of your site, e.g. /blog
url: "libewa.xyz" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
- { platform: github,  user_url: "https://github.com/libewa" }
- { platform: codeberg, user_url: "https://twitter.com/libewa" }

# Build settings
plugins:
- jekyll-feed
- jekyll-remote-theme
- jemoji
- jekyll-default-layout
- jekyll-sitemap