title: libewa.xyz
author:
  name: Linus Warnatz
  email: linus@libewa.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Mediocre Swift and TypeScript code,
  with a bit of Python and C++.
baseurl: "" # the subpath of your site, e.g. /blog
url: "libewa.xyz" # the base hostname & protocol for your site, e.g. http://example.com

social_links:
- { platform: github,  user_url: "https://github.com/libewa" }
- { platform: codeberg, user_url: "https://codeberg.com/libewa" }
- { platform: github, title: "Gists", user_url: "https://gist.github.com/libewa" }
static_links:
- { title: "Home", url: "/" }
- { title: "About", url: "/about" }
- { title: "Contact", url: "/contact" }
- { title: "RSS", url: "/feed.xml" }

tag_page_layout: tag
tag_page_dir: tag
show_excerpts: true
show_page_titles: true

# Build settings
theme: jekyll-glass
plugins:
- jekyll-feed
- jemoji
- jekyll-default-layout
- jekyll-tagging
- jekyll-sitemap