name: libewa.xyz
author:
  name: Linus Warnatz
  email: linus@libewa.xyz
description: >- # this means to ignore newlines until "baseurl:"
  Mediocre Swift and TypeScript code,
  with a bit of Python and C++.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://libewa.xyz" # the base hostname & protocol for your site, e.g. http://example.com
show_exerpts: true
header_pages:
  - about.md
minima:
  social_links:
  - { platform: github, user_url: "https://github.com/libewa" }
  - { platform: codeberg, user_url: "https://codeberg.org/libewa" }
  date_format: "%A, %Y-%m-%d %H:%M %Z"
  skin: "auto"

# Build settings
remote_theme: h01000110/windows-95
plugins:
- jekyll-feed
- jekyll-remote-theme

